/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    public String getGreeting() {
        return "Hello world.";
    }
    public void getJDBC() 
    {
    	try 
    	{
    	 Class.forName("org.sqlite.JDBC");
    	 System.out.println("JDBC SQLite succesfully installed");
    	}
    	catch (ClassNotFoundException e)
    	{
    	 System.out.println("Total Failure in getting JDBC SQLite");
    	}
    }

    public static void main(String[] args) {
    	App app=new App();
    	app.getJDBC();
        System.out.println(app.getGreeting());
    }
}
