version: "3.7"
services:
  scalapp:
    image: jackson/task2s
    command: sbt run
    ports:
    - 9000:9000
  ngrokapp:
    image: wernight/ngrok
    volumes:
    - ./ngrok.yml:/home/ngrok/.ngrok2/ngrok.yml
    ports:
    - 4040:4040
    command: ["ngrok", "http", "scalapp:9000", "--domain=muskrat-cute-multiply.ngrok-free.app"]
